### ISSUE TITLE
`create_salient_task_key` method does not handle None value correctly

### ISSUE THREAD

**Issue by Curlykonda** [kunhanda/task_ambiguity#2]
# Problem
In the case of generating examples without providing an explicit `salient_task`, the `set_salient_task` method in `Prompt.py` does not work as expected because `salient_task_a_or_b = None` (c.f. [line 144](https://github.com/kunhanda/task_ambiguity/blob/main/prompt.py#L144)). When calling `create_salient_task_key` in [line 118](https://github.com/kunhanda/task_ambiguity/blob/main/instruction.py#L118), the method does not handle the None value (c.f. [line 139](https://github.com/kunhanda/task_ambiguity/blob/1667ceb2ad213a97e8b65e183dff12d42ee75644/instruction.py#L139)) and would always return `key_task_label = query.task_b_label`. 

I think this is undesired behaviour as it would systematically exclude the possibility of `key_task_label = query.task_a_label`. 

# Proposed Solution
There are different options to address this, for instance, by randomly choosing between `task_a` and `task_b` if `salient_task_a_or_b = None` in the `create_salient_task_key` method. ([c.f.](https://github.com/kunhanda/task_ambiguity/blob/1667ceb2ad213a97e8b65e183dff12d42ee75644/instruction.py#L127))

**Comment by kunhanda** [comment]
Note that this function wasn't intended to be used in a standalone way--it is only used in the case of a salient task being set. In our experiments we did conduct tests without a salient task, however, these were limited to only two ambiguous examples + test example. We used a separate function ```run_two_feature_tests_with_two_set()``` which does not account for the salient task (i.e. ```salient_task = None```). However if you'd like to add a PR to do this we'd be happy to review and incorporate.
